version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "05:00"
    assignees:
      - "cdce8p"
    open-pull-requests-limit: 10
    rebase-strategy: "disabled"
    # Always use only the latest version
    versioning-strategy: increase
    # Maintain allow list to prevent updates to mypy requirements
    allow:
      - dependency-name: "packaging"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "05:00"
    assignees:
      - "cdce8p"
    open-pull-requests-limit: 10
    rebase-strategy: "disabled"
