name: Tag version

on:
  workflow_dispatch:
    inputs:
      name:
        type: string
        required: true
        default: 1.18.0a8
      commit:
        type: string
        default: origin/master
        required: true

jobs:
  tag_version:
    name: Tag new mypy-dev version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v6
        name: Install Python
        with:
          python-version: "3.13"
      - uses: actions/create-github-app-token@a8d616148505b5069dccd32f177bb87d7f39123b # v2.1.1
        id: app-token
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}
          permission-contents: write # push branch to Github
      - uses: actions/checkout@v5
        with:
          submodules: recursive
          token: ${{ steps.app-token.outputs.token }}
      - name: Set git config
        run: |
          git config --global user.name "${{ vars.BOT_NAME }}"
          git config --global user.email "${{ vars.BOT_EMAIL }}"
      - name: Fetch and checkout
        run: |
          git -C mypy fetch origin --no-tags -t master
          echo "---"
          git -C mypy checkout --detach ${{ inputs.commit }}
      # - name: Get new tag version
      #   id: new-tag
      #   run: python scripts/new_tag.py
      - name: Commit and push
        run: |
          git add --update
          git commit -m "Update mypy commit"
          tag_name="${{ inputs.name }}"
          git tag "${tag_name}"  # TODO <= !!
          git push origin main "${tag_name}"
